language: php
php:
  - '7.0'
  - '7.1'
install: composer install
script:
  # Lint PHP files
  - find ./ -name '*.php' ! -path '*vendor/*' ! -path '*var/cache/*' -print0 | xargs -0 -n1 -P4 php -l
  # Check coding standard
  - vendor/bin/php-cs-fixer fix --dry-run --config=.php_cs.dist -v --using-cache=no
  - vendor/bin/phpunit
  - vendor/bin/phpunit -c phpunit-integration.xml
  # See https://github.com/sensiolabs/security-checker/pull/77#issuecomment-290733113
  - php bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
